<?php

namespace RegistroBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroRepository extends EntityRepository
{

    public function findAllSeleccion($biomat)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT r FROM RegistroBundle:Registro r
                    WHERE r.activo = :activo
                    AND r.biomat = :biomat
                    ORDER BY r.paterno ASC"
            )
            ->setParameter('activo', 1)
            ->setParameter('biomat', $biomat)
        ->getResult();
    }

}
